# Generated by Django 5.2.12 on 2026-04-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=10, unique=True, verbose_name='كود المحافظة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم عربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم إنجليزي')),
                ('has_data', models.BooleanField(default=False, verbose_name='يوجد بيانات تعديات')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['pcode'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=12, unique=True, verbose_name='كود المركز')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم عربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم إنجليزي')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='violations.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مركز',
                'verbose_name_plural': 'المراكز الإدارية',
                'ordering': ['governorate', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100, verbose_name='اسم المركز')),
                ('village', models.CharField(max_length=200, verbose_name='القرية / المدينة')),
                ('village_pcode', models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='كود القرية (CAPMAS)')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='الرمز')),
                ('occupant', models.CharField(max_length=200, verbose_name='اسم المستغل')),
                ('basin', models.CharField(max_length=300, verbose_name='اسم الحوض')),
                ('description', models.CharField(db_index=True, max_length=500, verbose_name='وصف الاستغلال')),
                ('area_outside', models.FloatField(default=0, verbose_name='المسطح خارج الحياض م²')),
                ('area_public', models.FloatField(default=0, verbose_name='تعدي على المنفعة العامة م²')),
                ('area_nile_bank', models.FloatField(default=0, verbose_name='تعدي على جسر نهر النيل م²')),
                ('area_total', models.FloatField(db_index=True, default=0, verbose_name='المسطح الإجمالي م²')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('geo_exact', models.BooleanField(default=False, verbose_name='إحداثيات دقيقة (من الشيب فايل)')),
                ('import_batch', models.CharField(blank=True, default='', max_length=100, verbose_name='دفعة الاستيراد')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='violations.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'تعدٍّ',
                'verbose_name_plural': 'التعديات على نهر النيل',
                'ordering': ['governorate', 'district_name', 'village'],
                'indexes': [models.Index(fields=['governorate', 'district_name'], name='violations__governo_dde421_idx'), models.Index(fields=['village_pcode'], name='violations__village_e20c55_idx'), models.Index(fields=['area_total'], name='violations__area_to_40355c_idx')],
            },
        ),
    ]
