# Generated by Django 5.2.12 on 2026-04-09 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'مشاهد — عرض البيانات فقط'), ('data_entry', 'مدخل بيانات — إضافة وتعديل'), ('supervisor', 'مشرف — مراجعة وموافقة'), ('manager', 'مدير — صلاحيات كاملة')], default='viewer', max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='ViolationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='violations/%Y/%m/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'صور التعديات',
            },
        ),
        migrations.CreateModel(
            name='ViolationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'الملاحظات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'تعدٍّ', 'verbose_name_plural': 'التعديات على نهر النيل'},
        ),
        migrations.RemoveIndex(
            model_name='violation',
            name='violations__area_to_40355c_idx',
        ),
        migrations.AddField(
            model_name='violation',
            name='field_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات ميدانية'),
        ),
        migrations.AddField(
            model_name='violation',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المراجعة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_violations', to=settings.AUTH_USER_MODEL, verbose_name='راجعه'),
        ),
        migrations.AddField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('pending', 'في انتظار الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='approved', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإدخال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_violations', to=settings.AUTH_USER_MODEL, verbose_name='أُدخل بواسطة'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='has_data',
            field=models.BooleanField(default=False, verbose_name='يوجد بيانات'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='geo_exact',
            field=models.BooleanField(default=False, verbose_name='إحداثيات دقيقة'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='village_pcode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='كود القرية'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['status'], name='violations__status_f07abc_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='violations.governorate', verbose_name='المحافظة المسؤول عنها'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='violationimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رُفعت بواسطة'),
        ),
        migrations.AddField(
            model_name='violationimage',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='violations.violation', verbose_name='التعدي'),
        ),
        migrations.AddField(
            model_name='violationnote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='violationnote',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='violations.violation', verbose_name='التعدي'),
        ),
    ]
