# Generated by Django 5.2.12 on 2026-04-13 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_userprofile_violationimage_violationnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('add', 'إضافة سجل'), ('edit', 'تعديل سجل'), ('approve', 'موافقة على سجل'), ('reject', 'رفض سجل'), ('delete', 'حذف سجل'), ('export', 'تصدير تقرير'), ('import', 'استيراد بيانات'), ('login_fail', 'محاولة دخول فاشلة')], max_length=20, verbose_name='الحدث')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='الهدف')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التوقيت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجل الأنشطة',
                'ordering': ['-timestamp'],
            },
        ),
    ]
