# Generated by Django 6.0.5 on 2026-05-18 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0005_violation_survey_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_number', models.CharField(help_text='مثال: 14717 لسنة 1987', max_length=100, verbose_name='رقم القرار')),
                ('date_from', models.DateField(verbose_name='تاريخ البداية')),
                ('date_to', models.DateField(blank=True, help_text='اتركه فارغاً إذا كان سارياً حتى الآن', null=True, verbose_name='تاريخ النهاية')),
                ('rate_per_year', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الفئة السنوية (جنيه/م²)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'قرار وزاري',
                'verbose_name_plural': 'القرارات الوزارية',
                'ordering': ['order', 'date_from'],
            },
        ),
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نوع الاستغلال')),
                ('decision', models.CharField(choices=[('148', 'القرار 148 لسنة 2026 — ترخيص'), ('149', 'القرار 149 لسنة 2026 — مخالفة')], default='149', max_length=10, verbose_name='القرار')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='البند')),
                ('rate_warraq', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='منطقة الوراق')),
                ('rate_aswan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='أسوان-الأقصر-أسيوط-المنصورة')),
                ('rate_other', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='باقي المحافظات النيلية')),
                ('rate_urban_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='داخل الحيز العمراني')),
                ('rate_urban_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='خارج الحيز العمراني')),
                ('unit', models.CharField(default='م²', max_length=20, verbose_name='وحدة الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'نوع استغلال',
                'verbose_name_plural': 'أنواع الاستغلال',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'قطعة أرض', 'verbose_name_plural': 'أراضي طرح النهر'},
        ),
        migrations.AlterModelOptions(
            name='violationimage',
            options={'verbose_name': 'صورة', 'verbose_name_plural': 'صور القطع'},
        ),
        migrations.AlterField(
            model_name='violation',
            name='area_nile_bank',
            field=models.FloatField(default=0, verbose_name='مساحة على جسر النهر م²'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='area_public',
            field=models.FloatField(default=0, verbose_name='مساحة على المنفعة العامة م²'),
        ),
        migrations.AlterField(
            model_name='violationimage',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='violations.violation', verbose_name='قطعة الأرض'),
        ),
        migrations.AlterField(
            model_name='violationnote',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='violations.violation', verbose_name='قطعة الأرض'),
        ),
        migrations.CreateModel(
            name='ViolationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant_name', models.CharField(max_length=300, verbose_name='اسم المستغل')),
                ('activity_desc', models.CharField(blank=True, max_length=500, verbose_name='وصف النشاط')),
                ('zone', models.CharField(choices=[('warraq', 'منطقة الوراق'), ('aswan', 'أسوان - الأقصر - أسيوط - المنصورة'), ('other', 'باقي المحافظات النيلية'), ('urban_in', 'داخل الحيز العمراني'), ('urban_out', 'خارج الحيز العمراني')], default='other', max_length=20, verbose_name='المنطقة الجغرافية')),
                ('area', models.FloatField(verbose_name='المساحة المستغلة (م²)')),
                ('date_from', models.DateField(verbose_name='تاريخ بداية الاستغلال')),
                ('date_to', models.DateField(blank=True, help_text='اتركه فارغاً إذا كان مستمراً', null=True, verbose_name='تاريخ نهاية الاستغلال')),
                ('is_ongoing', models.BooleanField(default=False, verbose_name='مستمر حتى الآن')),
                ('rate_per_year', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='الفئة السنوية (جنيه/م²)')),
                ('calculated_value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='مقابل الانتفاع المحسوب (جنيه)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='ما تم سداده (جنيه)')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('import_source', models.CharField(blank=True, max_length=100, verbose_name='مصدر الاستيراد')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages_created', to=settings.AUTH_USER_MODEL, verbose_name='أُدخل بواسطة')),
                ('usage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='violations.usagetype', verbose_name='نوع الاستغلال')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='violations.violation', verbose_name='قطعة الأرض')),
            ],
            options={
                'verbose_name': 'سجل استغلال',
                'verbose_name_plural': 'سجلات الاستغلال',
                'ordering': ['violation', 'date_from'],
            },
        ),
    ]
