# Generated by Django 5.2.12 on 2026-05-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0008_remove_usagetype_price_zone1_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationusage',
            name='amount_before_2021',
            field=models.DecimalField(decimal_places=2, default=0, help_text='قيمة مقطوعة للفترة السابقة لتولى الوزارة', max_digits=16, verbose_name='مقابل انتفاع قبل 17/10/2021 (جنيه)'),
        ),
    ]
