# Generated by Django 5.2.12 on 2026-05-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0009_add_amount_before_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationusage',
            name='basis',
            field=models.CharField(choices=[('148', 'القرار 148 لسنة 2026 — ترخيص'), ('149', 'القرار 149 لسنة 2026 — مخالفة')], default='149', max_length=10, verbose_name='أساس الاستغلال'),
        ),
    ]
