# Generated by Django 5.2.12 on 2026-05-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0012_add_decision_rate_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministrydecision',
            name='rate_aswan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='أسوان - الأقصر - أسيوط - المنصورة'),
        ),
        migrations.AddField(
            model_name='ministrydecision',
            name='rate_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='باقي المحافظات النيلية'),
        ),
        migrations.AddField(
            model_name='ministrydecision',
            name='rate_urban_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='داخل الحيز العمراني'),
        ),
        migrations.AddField(
            model_name='ministrydecision',
            name='rate_urban_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='خارج الحيز العمراني'),
        ),
        migrations.AddField(
            model_name='ministrydecision',
            name='rate_warraq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='منطقة الوراق'),
        ),
    ]
