# Generated by Django 5.2.12 on 2026-05-28 20:21

from django.db import migrations


def set_193_zone_rates(apps, schema_editor):
    MinistryDecision = apps.get_model('violations', 'MinistryDecision')
    try:
        d = MinistryDecision.objects.get(decision_number__contains='193 لسنة 2024')
        d.rate_warraq = 600.00
        d.rate_aswan = 180.00
        d.rate_other = 180.00
        d.rate_urban_in = 240.00
        d.rate_urban_out = 60.00
        d.save()
    except MinistryDecision.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0013_add_decision_zone_rates'),
    ]

    operations = [
        migrations.RunPython(set_193_zone_rates, migrations.RunPython.noop),
    ]
