# Generated by Django 5.2.12 on 2026-05-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0014_populate_193_zone_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='السنة')),
                ('date_acquired', models.DateField(verbose_name='تاريخ الالتقاط')),
                ('image', models.ImageField(upload_to='satellite/', verbose_name='الصورة')),
                ('cloud_cover', models.FloatField(default=0, verbose_name='الغطاء السحابي')),
                ('bounds_west', models.FloatField(default=0, verbose_name='حد غرب')),
                ('bounds_south', models.FloatField(default=0, verbose_name='حد جنوب')),
                ('bounds_east', models.FloatField(default=0, verbose_name='حد شرق')),
                ('bounds_north', models.FloatField(default=0, verbose_name='حد شمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التخزين')),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='violations.violation', verbose_name='القطعة')),
            ],
            options={
                'verbose_name': 'صورة قمر صناعي',
                'verbose_name_plural': 'صور الأقمار الصناعية',
                'ordering': ['-year', '-date_acquired'],
                'unique_together': {('violation', 'year')},
            },
        ),
    ]
