# Generated by Django 5.2.12 on 2026-06-03 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0015_satellite_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministrydecision',
            name='basis',
            field=models.CharField(blank=True, choices=[('148', 'ترخيص'), ('149', 'مخالفة')], help_text='ترخيص (148) أو مخالفة (149)', max_length=10, null=True, verbose_name='أساس القرار'),
        ),
        migrations.AddField(
            model_name='ministrydecision',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='decisions/', verbose_name='ملف القرار (PDF)'),
        ),
        migrations.AlterField(
            model_name='usagetype',
            name='decision',
            field=models.CharField(choices=[('148', 'ترخيص'), ('149', 'مخالفة')], default='149', max_length=10, verbose_name='القرار'),
        ),
        migrations.AlterField(
            model_name='violationusage',
            name='basis',
            field=models.CharField(choices=[('148', 'ترخيص'), ('149', 'مخالفة')], default='149', max_length=10, verbose_name='أساس الاستغلال'),
        ),
        migrations.CreateModel(
            name='DecisionUsageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_warraq', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='منطقة الوراق')),
                ('rate_aswan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='أسوان-الأقصر-أسيوط-المنصورة')),
                ('rate_other', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='باقي المحافظات النيلية')),
                ('rate_urban_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='داخل الحيز العمراني')),
                ('rate_urban_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='خارج الحيز العمراني')),
                ('unit', models.CharField(default='م²', max_length=20, verbose_name='وحدة الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('ministry_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_rates', to='violations.ministrydecision', verbose_name='القرار الوزاري')),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_rates', to='violations.usagetype', verbose_name='نوع الاستغلال')),
            ],
            options={
                'verbose_name': 'سعر استغلال للقرار',
                'verbose_name_plural': 'أسعار الاستغلال لكل قرار',
                'unique_together': {('ministry_decision', 'usage_type')},
            },
        ),
    ]
