# Generated by Django 5.2.12 on 2026-06-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0016_ministrydecision_basis_ministrydecision_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministrydecision',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='decisions/excel/', verbose_name='ملف Excel للأسعار'),
        ),
    ]
