# Generated by Django 5.2.12 on 2026-06-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0017_ministrydecision_excel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionusagerate',
            name='unit',
            field=models.CharField(default='م²', max_length=100, verbose_name='وحدة الحساب'),
        ),
        migrations.AlterField(
            model_name='usagetype',
            name='unit',
            field=models.CharField(default='م²', max_length=100, verbose_name='وحدة الحساب'),
        ),
    ]
