# Generated by Django 5.2.12 on 2026-06-04 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0018_alter_decisionusagerate_unit_alter_usagetype_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionusagerate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='السعر'),
        ),
        migrations.CreateModel(
            name='DecisionRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنطقة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('ministry_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='violations.ministrydecision', verbose_name='القرار الوزاري')),
            ],
            options={
                'verbose_name': 'منطقة قرار',
                'verbose_name_plural': 'مناطق القرارات',
                'ordering': ['ministry_decision', 'order', 'name'],
                'unique_together': {('ministry_decision', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='decisionusagerate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='decisionusagerate',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_rates', to='violations.decisionregion', verbose_name='المنطقة'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionusagerate',
            unique_together={('ministry_decision', 'usage_type', 'region')},
        ),
        migrations.RemoveField(
            model_name='decisionusagerate',
            name='rate_aswan',
        ),
        migrations.RemoveField(
            model_name='decisionusagerate',
            name='rate_other',
        ),
        migrations.RemoveField(
            model_name='decisionusagerate',
            name='rate_urban_in',
        ),
        migrations.RemoveField(
            model_name='decisionusagerate',
            name='rate_urban_out',
        ),
        migrations.RemoveField(
            model_name='decisionusagerate',
            name='rate_warraq',
        ),
    ]
