# Generated by Django 5.2.12 on 2026-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0019_decisionusagerate_rate_decisionregion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationusage',
            name='decision_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='قائمة: {decision_id, region_id, usage_type_id, days, rate, amount}', verbose_name='تفصيل الحساب حسب القرار'),
        ),
    ]
